// Generated by CoffeeScript 1.7.1

/* 
JVox Experimental Voxel Renderer

----
The MIT License (MIT)

Copyright (c) 2014 yvt

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 */

(function() {
  var PerspectiveCamera, PseudoThreeDRenderer, Utils, VoxelField;

  Utils = {
    normalize2DArray: function(x, y) {
      var sq;
      sq = 1 / Math.sqrt(x * x + y * y);
      return [x * sq, y * sq];
    }
  };

  VoxelField = (function() {
    function VoxelField(data, width, height) {
      var d, index, x, y, _i, _j, _ref, _ref1;
      this.width = width;
      this.height = height;
      this.data = new Uint8Array(data);
      this.addrIndex = [];
      index = 0;
      d = this.data;
      for (y = _i = 0, _ref = this.height - 1; _i <= _ref; y = _i += 1) {
        for (x = _j = 0, _ref1 = this.width - 1; _j <= _ref1; x = _j += 1) {
          this.addrIndex.push(index);
          while (d[index] !== 0) {
            index += d[index] * 4;
          }
          index += (d[index + 2] - d[index + 1] + 2) << 2;
        }
      }
      return;
    }

    VoxelField.prototype.getAddressForColumn = function(x, y) {
      if (x < 0 || y < 0 || x >= this.width || y >= this.height) {
        return -1;
      }
      return this.addrIndex[x + y * this.width];
    };

    return VoxelField;

  })();

  PerspectiveCamera = (function() {
    function PerspectiveCamera() {
      this.fovX = 90 * Math.PI / 180;
      this.fovY = 50 * Math.PI / 180;
      this.eye = {
        x: 0,
        y: 0,
        z: 0
      };
      this.target = {
        x: 1,
        y: 1,
        z: 1
      };
      return;
    }

    PerspectiveCamera.prototype.renderColumnsForPseudoThreeD = function(width, height, callback) {
      var ddx, ddy, dx, dy, eyeX, eyeY, eyeZ, fovX, fovY, frontX, frontY, midY, ndx, ndy, offs, sideX, sideY, x, yProjector, zScale, _i, _ref, _ref1, _ref2;
      frontX = this.target.x - this.eye.x;
      frontY = this.target.y - this.eye.y;
      _ref = Utils.normalize2DArray(frontX, frontY), frontX = _ref[0], frontY = _ref[1];
      sideX = frontY;
      sideY = -frontX;
      fovX = Math.tan(this.fovX * 0.5);
      sideX *= fovX;
      sideY *= fovX;
      dx = frontX - sideX;
      dy = frontY - sideY;
      ddx = sideX * 2 / width;
      ddy = sideY * 2 / width;
      fovY = Math.tan(this.fovY * 0.5);
      eyeX = this.eye.x;
      eyeY = this.eye.y;
      eyeZ = this.eye.z;
      zScale = height / (fovY * 2);
      midY = height * 0.5;
      offs = eyeX * frontX + eyeY * frontY - 0.00001;
      yProjector = function(x, y, z) {
        var viewZ;
        viewZ = x * frontX + y * frontY - offs;
        return (z - eyeZ) * zScale / viewZ + midY;
      };
      for (x = _i = 0, _ref1 = width - 1; _i <= _ref1; x = _i += 1) {
        _ref2 = Utils.normalize2DArray(dx, dy), ndx = _ref2[0], ndy = _ref2[1];
        callback(eyeX, eyeY, ndx, ndy, x, yProjector);
        dx += ddx;
        dy += ddy;
      }
    };

    return PerspectiveCamera;

  })();

  PseudoThreeDRenderer = (function() {
    function PseudoThreeDRenderer(field, width, height) {
      this.field = field;
      this.width = width;
      this.height = height;
      this.width = this.width | 0;
      this.height = this.height | 0;
      return;
    }

    PseudoThreeDRenderer.prototype.renderColumn = function(pixels, x, y, dx, dy, drawX, proj) {
      var bottomColorEnd, bottomColorStart, colorIndex, drawH, drawW, fdata, field, fill, haltCheck, index, invDx, invDy, ix, iy, lenBottom, lenTop, nix, niy, numChunks, nx, ny, time, timeToNextX, timeToNextY, topColorEnd, topColorStart, y1, y2, z, _i, _j, _k, _ref;
      drawW = this.width;
      drawH = this.height;
      field = this.field;
      fdata = field.data;
      if (Math.abs(dx) < 0.0000001) {
        dx += 0.00001;
      }
      if (Math.abs(dy) < 0.0000001) {
        dy += 0.00001;
      }
      invDx = 1 / dx;
      invDy = 1 / dy;
      ix = Math.floor(x);
      iy = Math.floor(y);
      fill = function(y1, y2, r, g, b) {
        var clr, ind, yy, _i, _ref;
        if (y1 >= y2) {
          return;
        }
        if (y1 < 0) {
          y1 = 0;
        }
        if (y2 > drawH) {
          y2 = drawH;
        }
        if (y1 >= drawH) {
          return;
        }
        if (y2 <= 0) {
          return;
        }
        y1 |= 0;
        y2 |= 0;
        ind = drawX + y1 * drawW;
        clr = b | (g << 8) | (r << 16) | 0xff000000;
        for (yy = _i = y1, _ref = y2 - 1; _i <= _ref; yy = _i += 1) {
          if (pixels[ind] === 0) {
            pixels[ind] = clr;
          }
          ind += drawW;
        }
      };
      for (haltCheck = _i = 0; _i <= 63; haltCheck = ++_i) {
        if ((dx >= 0 ? x >= field.width : x <= 0) || (dy >= 0 ? y >= field.height : y <= 0)) {
          return;
        }
        timeToNextX = (dx >= 0 ? ix + 1 - x : ix - x) * invDx;
        timeToNextY = (dy >= 0 ? iy + 1 - y : iy - y) * invDy;
        if (timeToNextX < timeToNextY) {
          time = timeToNextX;
          nix = dx >= 0 ? ix + 1 : ix - 1;
          niy = iy;
          nx = dx >= 0 ? nix : ix;
          ny = y + dy * time;
        } else {
          time = timeToNextY;
          nix = ix;
          niy = dy >= 0 ? iy + 1 : iy - 1;
          nx = x + dx * time;
          ny = dy >= 0 ? niy : iy;
        }
        index = field.getAddressForColumn(ix, iy);
        if (index >= 0) {
          while (true) {
            numChunks = fdata[index];
            topColorStart = fdata[index + 1];
            topColorEnd = fdata[index + 2];
            z = topColorStart;
            y1 = proj(nx, ny, z);
            y2 = proj(x, y, z);
            fill(y1, y2, fdata[index + 4], fdata[index + 5], fdata[index + 6]);
            if (numChunks === 0) {
              break;
            }
            lenBottom = topColorEnd - topColorStart + 1;
            lenTop = numChunks - 1 - lenBottom;
            bottomColorEnd = fdata[index + numChunks * 4 + 3];
            bottomColorStart = bottomColorEnd - lenTop;
            if (bottomColorStart < bottomColorEnd) {
              index += numChunks * 4 - 4;
              z = bottomColorEnd;
              y1 = proj(x, y, z);
              y2 = proj(nx, ny, z);
              fill(y1, y2, fdata[index], fdata[index + 1], fdata[index + 2]);
              index += 4;
            } else {
              z = topColorEnd + 1;
              y2 = proj(nx, ny, z);
              y1 = proj(x, y, z);
              fill(y1, y2, fdata[index + 4], fdata[index + 5], fdata[index + 6]);
              index += numChunks * 4;
            }
          }
        }
        ix = nix;
        iy = niy;
        x = nx;
        y = ny;
        index = field.getAddressForColumn(ix, iy);
        if (index >= 0) {
          while (true) {
            numChunks = fdata[index];
            topColorStart = fdata[index + 1];
            topColorEnd = fdata[index + 2];
            colorIndex = index + 4;
            y2 = proj(x, y, topColorStart);
            for (z = _j = topColorStart; _j <= topColorEnd; z = _j += 1) {
              y1 = y2;
              y2 = proj(x, y, z + 1);
              fill(y1, y2, fdata[colorIndex] >> 1, fdata[colorIndex + 1] >> 1, fdata[colorIndex + 2] >> 1);
              colorIndex += 4;
            }
            if (numChunks === 0) {
              break;
            }
            index += numChunks * 4;
            lenBottom = topColorEnd - topColorStart + 1;
            lenTop = numChunks - 1 - lenBottom;
            bottomColorEnd = fdata[index + 3];
            bottomColorStart = bottomColorEnd - lenTop;
            if (bottomColorEnd > bottomColorStart) {
              y2 = proj(x, y, bottomColorStart);
              for (z = _k = bottomColorStart, _ref = bottomColorEnd - 1; _k <= _ref; z = _k += 1) {
                y1 = y2;
                y2 = proj(x, y, z + 1);
                fill(y1, y2, fdata[colorIndex] >> 1, fdata[colorIndex + 1] >> 1, fdata[colorIndex + 2] >> 1);
                colorIndex += 4;
              }
            }
          }
        }
      }
    };

    PseudoThreeDRenderer.prototype.render = function(pixels, camera) {
      var i, _i, _ref;
      for (i = _i = 0, _ref = this.width * this.height - 1; _i <= _ref; i = _i += 1) {
        pixels[i] = 0;
      }
      camera.renderColumnsForPseudoThreeD(this.width, this.height, (function(_this) {
        return function(x, y, dx, dy, drawX, proj) {
          _this.renderColumn(pixels, x, y, dx, dy, drawX, proj);
        };
      })(this));
    };

    return PseudoThreeDRenderer;

  })();

  (function() {
    var arg, args, i, newPart, newSource, parts, source, _i, _ref;
    source = PseudoThreeDRenderer.prototype.renderColumn.toString();
    parts = source.split(/fill\((.*?)\);/);
    for (i = _i = 1, _ref = parts.length - 1; _i <= _ref; i = _i += 2) {
      arg = parts[i];
      args = arg.split(",");
      newPart = "var clr, ind, yy, y1, y2;";
      newPart += "y1 = " + args[0] + ";";
      newPart += "y2 = " + args[1] + ";";
      newPart += "if (y1 < 0) y1 = 0;";
      newPart += "if (y2 > drawH) y2 = drawH;";
      newPart += "if (y1 < drawH && y2 > 0) {";
      newPart += "y1 |= 0; y2 |= 0;";
      newPart += "ind = drawX + y1 * drawW | 0;";
      newPart += "clr = 255 - (haltCheck << 2);";
      newPart += "clr = (" + args[4] + ") | ((" + args[3] + ") << 8) | ((" + args[2] + ") << 16) | (clr << 24);";
      newPart += "for (yy = y1; yy < y2; yy = (yy + 1) | 0) {";
      newPart += "if (pixels[ind] === 0) pixels[ind] = clr;";
      newPart += "ind = (ind + drawW) | 0;";
      newPart += "}}";
      parts[i] = newPart;
    }
    newSource = parts.join("");
    return PseudoThreeDRenderer.prototype.renderColumn = eval("(" + newSource + ")");
  })();

  window.JVox = {
    VoxelField: VoxelField,
    PerspectiveCamera: PerspectiveCamera,
    PseudoThreeDRenderer: PseudoThreeDRenderer
  };

}).call(this);
